#!/usr/bin/env bash
set -euo pipefail

# ── Yojin Docker Setup ──────────────────────────────────────
# Quick start: ./docker-setup.sh
# This script builds the image, creates an .env file if needed,
# and starts the services.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env.docker"

echo ""
echo "  ╭──────────────────────────────────────╮"
echo "  │         Yojin — Docker Setup         │"
echo "  │   Personal AI Finance Agent          │"
echo "  ╰──────────────────────────────────────╯"
echo ""

# ── Step 1: Check prerequisites ──────────────────────────────
check_command() {
  if ! command -v "$1" &>/dev/null; then
    echo "Error: $1 is required but not installed."
    exit 1
  fi
}

check_command docker
check_command docker

if ! docker compose version &>/dev/null && ! docker-compose version &>/dev/null; then
  echo "Error: Docker Compose is required but not installed."
  exit 1
fi

echo "✓ Docker and Docker Compose found"

# ── Step 2: Create .env.docker if it doesn't exist ───────────
if [ ! -f "$ENV_FILE" ]; then
  echo ""
  echo "Creating .env.docker configuration file..."
  echo ""

  # Anthropic API Key
  read -rp "  Anthropic API Key (sk-ant-...): " ANTHROPIC_API_KEY
  echo ""

  # Slack (optional)
  read -rp "  Slack Bot Token (xoxb-..., or press Enter to skip): " SLACK_BOT_TOKEN
  SLACK_APP_TOKEN=""
  SLACK_SIGNING_SECRET=""
  if [ -n "$SLACK_BOT_TOKEN" ]; then
    read -rp "  Slack App Token (xapp-...): " SLACK_APP_TOKEN
    read -rp "  Slack Signing Secret: " SLACK_SIGNING_SECRET
  fi
  echo ""

  # Web port
  read -rp "  Web UI port [8080]: " WEB_PORT
  WEB_PORT="${WEB_PORT:-8080}"

  # Vault passphrase
  read -rsp "  Vault passphrase (encrypts credentials, press Enter for none): " YOJIN_VAULT_PASSPHRASE
  echo ""

  cat > "$ENV_FILE" <<EOF
# Yojin Docker Configuration
# Generated by docker-setup.sh

# ── AI Provider (required) ───────────────────────
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# ── Slack Channel (optional) ─────────────────────
SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}

# ── Ports ────────────────────────────────────────
WEB_PORT=${WEB_PORT}
YOJIN_PORT=3000

# ── Security ─────────────────────────────────────
YOJIN_VAULT_PASSPHRASE=${YOJIN_VAULT_PASSPHRASE}

# ── Logging ──────────────────────────────────────
YOJIN_LOG_LEVEL=info

# ── Timezone ─────────────────────────────────────
TZ=UTC
EOF

  echo ""
  echo "✓ Configuration saved to .env.docker"
  echo "  (edit this file anytime to update settings)"
else
  echo "✓ Using existing .env.docker"
fi

# ── Step 3: Build the image ──────────────────────────────────
echo ""
echo "Building Yojin Docker image..."
echo "(this may take a few minutes on first run)"
echo ""

docker compose --env-file "$ENV_FILE" build

echo ""
echo "✓ Image built successfully"

# ── Step 4: Start services ───────────────────────────────────
echo ""
echo "Starting Yojin..."
echo ""

docker compose --env-file "$ENV_FILE" up -d

echo ""
echo "  ╭──────────────────────────────────────╮"
echo "  │          Yojin is running!            │"
echo "  │                                       │"
echo "  │  Web UI:  http://localhost:${WEB_PORT:-8080}        │"
echo "  │  API:     http://localhost:3000        │"
echo "  │  Health:  http://localhost:3000/health │"
echo "  │                                       │"
echo "  │  Logs:    docker compose logs -f      │"
echo "  │  Stop:    docker compose down         │"
echo "  ╰──────────────────────────────────────╯"
echo ""

if [ -n "${SLACK_BOT_TOKEN:-}" ]; then
  echo "  Slack bot is enabled — invite @Yojin to a channel."
fi

echo ""
